databases:
  - name: chart-view
    databaseName: chart-view
    user: shishimai805
    region: singapore
    plan: free

services:
  - type: web
    name: chart-view
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn chartview.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chart-view
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


    autoDeploy: true